### ISSUE TITLE
SetInstrumentationKey doesn't appear to be working (Gives 'Please provide instrumentation key')

### ISSUE THREAD

**Issue by JamieBerghmans** [IvanJosipovic/BlazorApplicationInsights#109]
I checked out your Sample project and just replaced the cfg in index.html with an empty object.
Like so: `cfg: {}`

Then I went into Program.cs, removed the telemetry, and added SetInstrumentationKey
```
builder.Services.AddBlazorApplicationInsights(async applicationInsights =>
{
    await applicationInsights.SetInstrumentationKey("MyKeyHere");
    await applicationInsights.LoadAppInsights();
});
```

but I keep getting this warning in the browser
`Failed to initialize AppInsights JS SDK for instance appInsights - Please provide instrumentation key`

If I replace it directly in the index.html it works fine, but I'm trying to get the key from the appsettings since that's what gets replaced in my deployment scripts.

I tried with both the original .NET Core version the library was written in, and also the one I'm using (5.0.4), but the problem appears in both.

**Comment by abosquet** [comment]
Any update here? I have the same issue.

**Comment by JamieBerghmans** [comment]
Sadly not. As far as my testing could conclude, the problem is that AppInsights's js code was always being executed before page load (regardless of the -1). So I ended up setting a static load delay of 500ms which allows the interop to inject the key before the js loads. The drawback here is that it won't capture startup/pageload errors, but It's better than nothing. (For those wondering why I didn't just add a placeholder value there and then replace it on deploy in the pipeline. I considered this and talked it over with my supervisor but he decided against it).

**Comment by abosquet** [comment]
Thanks for your update. What I can say too is even if there is this warning in the browser App Insights get events from the web app.

**Comment by IvanJosipovic** [comment]
I have updated the readme with a new approach on how to set the instrumentation key

**Comment by pmonte** [comment]
Thanks, I update to 1.6 (was 1.5) modified the js in index and the code in program.cs but still doesn't work (I'm on Net 6). 
Looking in Console/Network I can see that the iKey sent is empty "".

**Comment by dannyBies** [comment]
If I use a delay of -1 the first request with Pageview and PageviewPerformance will fail and the next request succeeds but sends the first failure to AppInsights
```
"data": {
  "baseType": "MessageData",
  "baseData": {
    "ver": 2,
    "message": "AI (Internal): 100 message:\"Invalid Instrumentation key \"",
    "properties": {}
  }
}
```

When adding the 400ms delay it will send the correct date for Pageview and PageviewPerformance.


So using no delay results in 2 missed messages on opening the webapp + 1 error message that should not happen.
Using the delay results in the expected 2 messages to appear in AppInsights.


Adding a delay also seems to fix another issue, the `name` and `refUri` only have the correct values with a delay.

Using the default Blazor Wasm template
Without delay:
```
"data": {
    "baseType": "PageviewData",
    "baseData": {
        "ver": 2,
        "name": "BlazorApp1",
        "url": "http://localhost:5279/",
        "duration": "00:00:00.226",
        "properties": {
            "refUri": ""
         },
         "measurements": {},
         "id": "244a38de3c9344ed9351045b821a3843"
    }
}
```

With delay:
```
"data": {
    "baseType": "PageviewData",
    "baseData": {
        "ver": 2,
        "name": "Index",
        "url": "http://localhost:5279/",
        "duration": "00:00:00.249",
        "properties": {
            "refUri": "http://localhost:5279/"
         },
         "measurements": {},
         "id": "244a38de3c9344ed9351045b821a3843"
    }
}
```

**Comment by bc3** [comment]
We setup our solution according to Set Instrumentation Key Programmatically from the readme.
And our calls to AI are always with  ikey=""

<img width="950" alt="image" src="https://user-images.githubusercontent.com/2547576/184343060-e38020bd-5ba4-4d7b-843d-4f7c6faee93f.png">

and this of course returns a 400 

code in program.cs, and key is correctly filled in

```
var key = builderApp.Configuration.GetSection("ApplicationInsights").GetSection("InstrumentationKey").Value;

builderApp.Services.AddBlazorApplicationInsights(async applicationInsights =>
{
    await applicationInsights.SetInstrumentationKey(key);
    await applicationInsights.TrackPageView();
});
```
and then all needed scripts and imports in index.cshtml

we are on .NET (core) 6 and the 1.6 version of your package

**Comment by IvanJosipovic** [comment]
I have documented a new approach for Blazor WASM ASP.NET Hosted Projects in the Readme.
